### PR TITLE
Some improvement on reusable code and result display

### PR DESCRIPTION
**Pull request by ixna**
Here is my attempt to improve base code on code #1 and ux #2. Also python 3 compatible

### CODE REVIEW

**Review by shauryachawla — COMMENTED** [review]
Do we have to have nested ifs in the menu() function? Isn't it redundant?

**Comment by ixna** [comment]
yes you're right, i've updated the code ... actually i wanted to handle if user didn't input any, so it won't error when method int() is called :)

**Comment by shauryachawla** [comment]
@ixna it's still buggy! If I choose to view the latest 5 posts, I will only get to see 2, because the '2' that I enter as the option goes to the 'limit' argument for the get_rss function.

**Comment by ixna** [comment]
ouch, my bad, you're right, i've fixed that in my last commit

**Pull request closed without merging**
